name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      - name: Linter Python
        run: |
          flake8

      - name: Security check
        run: |
          bandit -r .

  build_packer:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Packer
        run: |
          packer build deploy_packer.pkr.hcl

      - name: Push to Docker Hub
        run: |
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: |
          docker tag your-local-image:latest ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/voting-app:latest
